### ISSUE TITLE
Table name should be case insensitive

### ISSUE THREAD

**Issue by lonng** [pingcap/tidb-lightning#143] opened 2019-03-14 06:51 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!
	
1. What did you do? If possible, provide a recipe for reproducing the error.

Generate test SQL files via dbgen with the template

	dbgen -i /dev/stdin -o . -t db1903_baofu.app_cashPlatform -n 1000 -r 100 -k 1 -j 40 --escape-backslash --time-zone Asia/Shanghai <<'SCHEMAEOF'
	CREATE TABLE _ (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT {{ rownum }},
	`orderNo` VARCHAR(128) DEFAULT NULL COMMENT '交易号' {{ rand.regex('[0-9a-z]{128}', 'i') }},
	`memberId` VARCHAR(512) DEFAULT NULL COMMENT '会员ID' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`businessType` VARCHAR(64) DEFAULT NULL COMMENT '业务类型' {{ rand.regex('[0-9a-z]{64}', 'i') }},
	`businessName` VARCHAR(512) DEFAULT NULL COMMENT '业务名称' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`productName` VARCHAR(512) DEFAULT NULL COMMENT '产品名称' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`productId` VARCHAR(10) DEFAULT NULL COMMENT '产品ID' {{ rand.regex('[0-9a-z]{10}', 'i') }},
	`categoryId` VARCHAR(10) DEFAULT NULL COMMENT '产品类别' {{ rand.regex('[0-9a-z]{10}', 'i') }},
	`amount` DECIMAL(18,8) DEFAULT '0.00000000' COMMENT '金额' {{ rand.regex('[0-9]{18}\.[0-9]{8}') }},
	`amountEncrypt` VARCHAR(512) DEFAULT NULL COMMENT '金额加密' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`payAmount` DECIMAL(18,8) DEFAULT '0.00000000' COMMENT '实际付款金额' {{ rand.regex('[0-9]{18}\.[0-9]{8}') }},
	`orderTime` DATETIME DEFAULT NULL COMMENT '单据创建时间' {{ rand.u31_timestamp() }},
	`createTime` DATETIME DEFAULT NULL COMMENT '创建时间' {{ rand.u31_timestamp() }},
	`createUserId` VARCHAR(512) DEFAULT NULL COMMENT '创建用户ID' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`state` INT(4) DEFAULT NULL COMMENT '状态  0:待付款|1:已付款|2:已完成|-1:失败' {{ rand.range_inclusive(0, 9999) }},
	`stateMsg` VARCHAR(1024) DEFAULT NULL COMMENT '状态原因' {{ rand.regex('[0-9a-z]{1024}', 'i') }},
	`updateTime` DATETIME DEFAULT NULL COMMENT '更新时间' {{ rand.u31_timestamp() }},
	`updateUserId` VARCHAR(512) DEFAULT NULL COMMENT '更新用户ID' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`isDelete` INT(4) DEFAULT '0' COMMENT '是否删除' {{ rand.range_inclusive(0, 9999) }},
	`deleteUserId` VARCHAR(512) DEFAULT NULL COMMENT '删除用户ID' {{ rand.regex('[0-9a-z]{512}', 'i') }},
	`deleteTime` DATETIME DEFAULT NULL COMMENT '删除时间' {{ rand.u31_timestamp() }},
	`appid` INT(8) DEFAULT NULL COMMENT '来源  0:PC|1:手机|99:出款' {{ rand.range_inclusive(0, 99999999) }},
	PRIMARY KEY(`id`),
	INDEX `pay_unique`(`orderNo`, `businessType`) USING BTREE
	) ENGINE = InnoDB AUTO_INCREMENT = 10405 DEFAULT CHARACTER SET = UTF8;
	SCHEMAEOF

2. What did you expect to see?

Lightning import table without any errors.

3. What did you see instead?

```
2019/03/14 14:33:22.427 main.go:65: [error] tidb lightning encountered error:table info app_cashplatform not found
github.com/pingcap/tidb-lightning/lightning/restore.(*RestoreController).restoreTables
        /home/jenkins/workspace/lightning_ghpr_build/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:452
github.com/pingcap/tidb-lightning/lightning/restore.(*RestoreController).restoreTables-fm
        /home/jenkins/workspace/lightning_ghpr_build/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:216
github.com/pingcap/tidb-lightning/lightning/restore.(*RestoreController).Run
        /home/jenkins/workspace/lightning_ghpr_build/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:225
github.com/pingcap/tidb-lightning/lightning.(*Lightning).run
        /home/jenkins/workspace/lightning_ghpr_build/go/src/github.com/pingcap/tidb-lightning/lightning/lightning.go:132
github.com/pingcap/tidb-lightning/lightning.(*Lightning).Run.func2
        /home/jenkins/workspace/lightning_ghpr_build/go/src/github.com/pingcap/tidb-lightning/lightning/lightning.go:83
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
```

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        (paste TiDB-Lightning version here)
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by glorv** [comment] 2020-08-25 10:29
since we have `mydumper.case-sensitive` config now, so shall we close this issue now? @kennytm

**Comment by kennytm** [comment] 2020-08-25 13:49
close if it is no longer reproducible.

**Closed** 2020-08-27 06:16 UTC
Labels: bug, difficulty/2-medium, priority/P0
