### ISSUE TITLE
[Bug Report] 4.0.6 backend tidb  importer CSV unknown columns in header

### ISSUE THREAD

**Issue by Zclhlmgqzc** [pingcap/tidb-lightning#410] opened 2020-09-28 10:20 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
4.0.6 导入 CSV 
```CSV
A123456789012345678901234567890123456789,B123456789012345678901234567890123456789,C123456789012345678901234567890123456789,D123456789012345678901234567890123456789,E123456789012345678901234567890123456789,F123456789012345678901234567890123456789,G123456789012345678901234567890123456789,H123456789012345678901234567890123456789,I123456789012345678901234567890123456789,J123456789012345678901234567890123456789,K123456789012345678901234567890123456789,L123456789012345678901234567890123456789,M123456789012345678901234567890123456789,N123456789012345678901234567890123456789,O123456789012345678901234567890123456789,P123456789012345678901234567890123456789,Q123456789012345678901234567890123456789,R123456789012345678901234567890123456789,S123456789012345678901234567890123456789,T123456789012345678901234567890123456789,U123456789012345678901234567890123456789,V123456789012345678901234567890123456789,W123456789012345678901234567890123456789,X123456789012345678901234567890123456789,Y12345678901234567890123456789012345678,Z
A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
```
报错
```
unknown columns in header [z]
github.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).parseColumnPermutations
	/home/jenkins/agent/workspace/ld_lightning_multi_branch_v4.0.6/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1513
github.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).initializeColumns
	/home/jenkins/agent/workspace/ld_lightning_multi_branch_v4.0.6/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1482
github.com/pingcap/tidb-lightning/lightning/restore.(*chunkRestore).encodeLoop
	/home/jenkins/agent/workspace/ld_lightning_multi_branch_v4.0.6/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1870
github.com/pingcap/tidb-lightning/lightning/restore.(*chunkRestore).restore
	/home/jenkins/agent/workspace/ld_lightning_multi_branch_v4.0.6/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1955
github.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).restoreEngine.func1
	/home/jenkins/agent/workspace/ld_lightning_multi_branch_v4.0.6/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1049
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
restore table `test`.`ROW_FLOW_D` failed
```

此时 26 个字段 总长度 1000
数据库/CSV字段 长度减少一位 
比如：Y12345678901234567890123456789012345678 改成 Y1234567890123456789012345678901234567 后
导入成功
此时 26 个字段 总长度 999

**字段数量、长度超过一定范围，会报错**
比如 64 个字段时 字段字符长度大于等于 954 时会报错
比如 65 个字段时 字段字符长度大于等于 953 时会报错

**4.0.4 版本没有这个问题** 4.0.5 4.0.6 会报错

2. What did you expect to see?
跟 4.0.4 版本一样导入成功
3. What did you see instead?

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        4.0.6
        ```

**Comment by kennytm** [comment] 2020-09-28 18:11
Thanks for the report. This is caused by incorrect use of `group_concat`. As a workaround, you could execute 

```sql
set global group_concat_max_len = 999999;
```

and then restart Lightning.

The fix for this (#412) is expected to be shipped in the next two version (4.0.8).

**Closed** 2020-10-09 11:42 UTC
Labels: bug
