### ISSUE TITLE
local backend import corrupt

### ISSUE THREAD

**Issue by nullnotnil** [pingcap/tidb-lightning#351] opened 2020-07-16 15:21 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

I imported the ontime data set using the `local` backend instead of `tikv-importer` (which worked without this error):

```bash
./bin/tidb-lightning -backend local -sorted-kv-dir {mytempdir} -check-requirements=false -server-mode=false -d ./ontime-data -tidb-host 127.0.0.1 -tidb-user root
```

2. What did you expect to see?

Success

3. What did you see instead?

```
[2020/07/16 09:14:33.758 -06:00] [ERROR] [restore.go:109] [-] [table=`ontime`.`ontime`] [status=analyzed] [error="analyze table failed: Error 1105: insufficient bytes to decode value"]
[2020/07/16 09:14:33.758 -06:00] [ERROR] [main.go:82] ["tidb lightning encountered error stack info"] [error="restore table `ontime`.`ontime` failed: analyze table failed: Error 1105: insufficient bytes to decode value"] [errorVerbose="Error 1105: insufficient bytes to decode value\ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/agent/workspace/build_lightning_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/agent/workspace/build_lightning_master/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\ngithub.com/pingcap/tidb-lightning/lightning/common.SQLWithRetry.Exec.func1\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/common/util.go:181\ngithub.com/pingcap/tidb-lightning/lightning/common.SQLWithRetry.perform\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/common/util.go:119\ngithub.com/pingcap/tidb-lightning/lightning/common.SQLWithRetry.Exec\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/common/util.go:179\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).analyzeTable\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1453\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).postProcess\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1129\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).restoreTable\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:777\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*RestoreController).restoreTables.func1\n\t/home/jenkins/agent/workspace/build_lightning_master/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:603\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nanalyze table failed\nrestore table `ontime`.`ontime` failed"]
[2020/07/16 09:14:33.758 -06:00] [ERROR] [main.go:83] ["tidb lightning encountered error"] [error="restore table `ontime`.`ontime` failed: analyze table failed: Error 1105: insufficient bytes to decode value"]
```

4. Versions of the cluster

TiDB-Lightning version (run `tidb-lightning -V`):

```
Release Version: v3.0.16-7-g73e48bb
Git Commit Hash: 73e48bb31db69c84eafc1a28fbaee8e9d03ff615
Git Branch: master
UTC Build Time: 2020-07-14 01:30:31
Go Version: go version go1.13 linux/amd64
```

TiKV-Importer version (run `tikv-importer -V`)

(not used)
        
TiKV version (run `tikv-server -V`):

```
TiKV 
Release Version:   4.1.0-alpha
Edition:           Community
Git Commit Hash:   8b1fc4fc67f6d74a46a86d731eb5c152cbf0dfa8
Git Commit Branch: master
UTC Build Time:    2020-07-14 01:06:28
Rust Version:      rustc 1.46.0-nightly (16957bd4d 2020-06-30)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```

TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-771-gca41972fb
Edition: Community
Git Commit Hash: ca41972fbac068c8a5de107d9075f09ac68842ac
Git Branch: master
UTC Build Time: 2020-07-14 02:41:21
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
 ```

Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by kennytm** [comment] 2020-07-17 04:01
PTAL @glorv

**Comment by glorv** [comment] 2020-07-17 08:22
@nullnotnil  Thank you for the report. I tried to reproduce this issue with same version of tidb/tikv but failed. So I'll appreciate if you can provide some information about the following:
- the table schema of `ontime`
- is this issue always recur when retry
- by change the param to `-backend tidb` and when finish manual run an `analyze table ontime`, can it success?
- if update tidb version to newer than `v4.0.0-GA`, will this still happen

**Comment by nullnotnil** [comment] 2020-07-17 13:55
> @nullnotnil Thank you for the report. I tried to reproduce this issue with same version of tidb/tikv but failed. So I'll appreciate if you can provide some information about the following:
> 
> * the table schema of `ontime`

I will upload the full mydumper backup for you. The schema is:
```sql
CREATE TABLE `ontime` (
  `Year` year DEFAULT NULL,
  `Quarter` tinyint(4) DEFAULT NULL,
  `Month` tinyint(4) DEFAULT NULL,
  `DayofMonth` tinyint(4) DEFAULT NULL,
  `DayOfWeek` tinyint(4) DEFAULT NULL,
  `FlightDate` date DEFAULT NULL,
  `UniqueCarrier` char(7) DEFAULT NULL,
  `AirlineID` int(11) DEFAULT NULL,
  `Carrier` char(2) DEFAULT NULL,
  `TailNum` varchar(50) DEFAULT NULL,
  `FlightNum` varchar(10) DEFAULT NULL,
  `OriginAirportID` int(11) DEFAULT NULL,
  `OriginAirportSeqID` int(11) DEFAULT NULL,
  `OriginCityMarketID` int(11) DEFAULT NULL,
  `Origin` char(5) DEFAULT NULL,
  `OriginCityName` varchar(100) DEFAULT NULL,
  `OriginState` char(2) DEFAULT NULL,
  `OriginStateFips` varchar(10) DEFAULT NULL,
  `OriginStateName` varchar(100) DEFAULT NULL,
  `OriginWac` int(11) DEFAULT NULL,
  `DestAirportID` int(11) DEFAULT NULL,
  `DestAirportSeqID` int(11) DEFAULT NULL,
  `DestCityMarketID` int(11) DEFAULT NULL,
  `Dest` char(5) DEFAULT NULL,
  `DestCityName` varchar(100) DEFAULT NULL,
  `DestState` char(2) DEFAULT NULL,
  `DestStateFips` varchar(10) DEFAULT NULL,
  `DestStateName` varchar(100) DEFAULT NULL,
  `DestWac` int(11) DEFAULT NULL,
  `CRSDepTime` int(11) DEFAULT NULL,
  `DepTime` int(11) DEFAULT NULL,
  `DepDelay` int(11) DEFAULT NULL,
  `DepDelayMinutes` int(11) DEFAULT NULL,
  `DepDel15` int(11) DEFAULT NULL,
  `DepartureDelayGroups` int(11) DEFAULT NULL,
  `DepTimeBlk` varchar(20) DEFAULT NULL,
  `TaxiOut` int(11) DEFAULT NULL,
  `WheelsOff` int(11) DEFAULT NULL,
  `WheelsOn` int(11) DEFAULT NULL,
  `TaxiIn` int(11) DEFAULT NULL,
  `CRSArrTime` int(11) DEFAULT NULL,
  `ArrTime` int(11) DEFAULT NULL,
  `ArrDelay` int(11) DEFAULT NULL,
  `ArrDelayMinutes` int(11) DEFAULT NULL,
  `ArrDel15` int(11) DEFAULT NULL,
  `ArrivalDelayGroups` int(11) DEFAULT NULL,
  `ArrTimeBlk` varchar(20) DEFAULT NULL,
  `Cancelled` tinyint(4) DEFAULT NULL,
  `CancellationCode` char(1) DEFAULT NULL,
  `Diverted` tinyint(4) DEFAULT NULL,
  `CRSElapsedTime` int(11) DEFAULT NULL,
  `ActualElapsedTime` int(11) DEFAULT NULL,
  `AirTime` int(11) DEFAULT NULL,
  `Flights` int(11) DEFAULT NULL,
  `Distance` int(11) DEFAULT NULL,
  `DistanceGroup` tinyint(4) DEFAULT NULL,
  `CarrierDelay` int(11) DEFAULT NULL,
  `WeatherDelay` int(11) DEFAULT NULL,
  `NASDelay` int(11) DEFAULT NULL,
  `SecurityDelay` int(11) DEFAULT NULL,
  `LateAircraftDelay` int(11) DEFAULT NULL,
  `FirstDepTime` varchar(10) DEFAULT NULL,
  `TotalAddGTime` varchar(10) DEFAULT NULL,
  `LongestAddGTime` varchar(10) DEFAULT NULL,
  `DivAirportLandings` varchar(10) DEFAULT NULL,
  `DivReachedDest` varchar(10) DEFAULT NULL,
  `DivActualElapsedTime` varchar(10) DEFAULT NULL,
  `DivArrDelay` varchar(10) DEFAULT NULL,
  `DivDistance` varchar(10) DEFAULT NULL,
  `Div1Airport` varchar(10) DEFAULT NULL,
  `Div1AirportID` int(11) DEFAULT NULL,
  `Div1AirportSeqID` int(11) DEFAULT NULL,
  `Div1WheelsOn` varchar(10) DEFAULT NULL,
  `Div1TotalGTime` varchar(10) DEFAULT NULL,
  `Div1LongestGTime` varchar(10) DEFAULT NULL,
  `Div1WheelsOff` varchar(10) DEFAULT NULL,
  `Div1TailNum` varchar(10) DEFAULT NULL,
  `Div2Airport` varchar(10) DEFAULT NULL,
  `Div2AirportID` int(11) DEFAULT NULL,
  `Div2AirportSeqID` int(11) DEFAULT NULL,
  `Div2WheelsOn` varchar(10) DEFAULT NULL,
  `Div2TotalGTime` varchar(10) DEFAULT NULL,
  `Div2LongestGTime` varchar(10) DEFAULT NULL,
  `Div2WheelsOff` varchar(10) DEFAULT NULL,
  `Div2TailNum` varchar(10) DEFAULT NULL,
  `Div3Airport` varchar(10) DEFAULT NULL,
  `Div3AirportID` int(11) DEFAULT NULL,
  `Div3AirportSeqID` int(11) DEFAULT NULL,
  `Div3WheelsOn` varchar(10) DEFAULT NULL,
  `Div3TotalGTime` varchar(10) DEFAULT NULL,
  `Div3LongestGTime` varchar(10) DEFAULT NULL,
  `Div3WheelsOff` varchar(10) DEFAULT NULL,
  `Div3TailNum` varchar(10) DEFAULT NULL,
  `Div4Airport` varchar(10) DEFAULT NULL,
  `Div4AirportID` int(11) DEFAULT NULL,
  `Div4AirportSeqID` int(11) DEFAULT NULL,
  `Div4WheelsOn` varchar(10) DEFAULT NULL,
  `Div4TotalGTime` varchar(10) DEFAULT NULL,
  `Div4LongestGTime` varchar(10) DEFAULT NULL,
  `Div4WheelsOff` varchar(10) DEFAULT NULL,
  `Div4TailNum` varchar(10) DEFAULT NULL,
  `Div5Airport` varchar(10) DEFAULT NULL,
  `Div5AirportID` int(11) DEFAULT NULL,
  `Div5AirportSeqID` int(11) DEFAULT NULL,
  `Div5WheelsOn` varchar(10) DEFAULT NULL,
  `Div5TotalGTime` varchar(10) DEFAULT NULL,
  `Div5LongestGTime` varchar(10) DEFAULT NULL,
  `Div5WheelsOff` varchar(10) DEFAULT NULL,
  `Div5TailNum` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
```

> * is this issue always recur when retry

Yes

> * by change the param to `-backend tidb` and when finish manual run an `analyze table ontime`, can it success?

I have not tried `-backend tidb` (it will take too long), but it works fine with backend importer.

> * if update tidb version to newer than `v4.0.0-GA`, will this still happen

This is against daily builds of master  - note the build time and hash.

**Comment by glorv** [comment] 2020-07-19 06:32
The root cause for this issue is that there are some value for type `varchar` are invalid utf-8 values, such as `\xe4NKNO\xe6`, the first and last char in this string are both non-unicode value that will cause analyze fail.

A minium step to reproduce this issue:
```
mysql> create table t (v1 varchar(30)) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
Query OK, 0 rows affected (0.09 sec)
```
```
$ python
>>> f = open("1.sql", "w")
>>> f.write('INSERT INTO `t` VALUES ("\xe4NKNO\xe6");\n')
>>> f.flush()
$ mysql -h 172.16.4.18 -uroot -P4000 -D t < 1.sql
```
```
mysql > analyze table t;
ERROR 1105 (HY000): other error: encoding failed
```

If I change the table schema without charset and collate, then we will fail at insert phase with:
```
[root@172.16.4.92 ontime2]# mysql -h 172.16.4.18 -uroot -P4000 -D t < 2.sql
ERROR 1366 (HY000) at line 1: incorrect utf8 value e44e4b4e4fe6(�NKNO�) for column v1
```

So this should be a collation issue. @wjhuang2016  PTAL

**Comment by glorv** [comment] 2020-07-19 06:36
BTW,  the bench data will fail in all three `local`, `importer`, `tidb` backend when analyze table

**Comment by nullnotnil** [comment] 2020-07-20 00:37
I haven't been able to reproduce this issue with importer, but I tried `tidb` today, and I can reproduce. So I think we can close this issue in tidb-lightning and keep the tidb issue open if that works for you?

**Comment by glorv** [comment] 2020-07-28 09:21
closed in favor of https://github.com/pingcap/tidb/issues/18680

**Closed by glorv** 2020-07-28 09:21 UTC
Labels: bug, difficulty/2-medium, priority/P1
