### ISSUE TITLE
incompatibility with tiflash

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb-lightning#322] opened 2020-05-23 14:25 UTC
## Bug Report

Using lightning with tiflash
it reports
```
[2020/05/23 21:55:29.311 +08:00] [ERROR] [restore.go:277] ["run failed"] [step=0] [error="TiKV (at 172.16.4.99:3930): strconv.ParseInt: parsing \"v4\": invalid syntax"]
[2020/05/23 21:55:29.311 +08:00] [ERROR] [restore.go:283] ["the whole procedure failed"] [takeTime=3.784156ms] [error="TiKV (at 172.16.4.99:3930): strconv.ParseInt: parsing \"v4\": invalid syntax"]
[2020/05/23 21:55:29.311 +08:00] [ERROR] [main.go:75] ["tidb lightning encountered error"] [error="TiKV (at 172.16.4.99:3930): strconv.ParseInt: parsing \"v4\": invalid syntax"] [errorVerbose="strconv.ParseInt: parsing \"v4\": invalid syntax\nTiKV (at 172.16.4.99:3930)\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*RestoreController).checkTiKVVersion.func1\n\t/home/jenkins/agent/workspace/release_tidb_4.0/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1212\ngithub.com/pingcap/tidb-lightning/lightning/backend.ForAllStores.func1\n\t/home/jenkins/agent/workspace/release_tidb_4.0/go/src/github.com/pingcap/tidb-lightning/lightning/backend/tikv.go:121\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/jenkins/agent/workspace/release_tidb_4.0/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"]
```
If I remove tiflash. then it starts OK

**Comment by kennytm** [comment] 2020-05-23 14:45
Duplicate of #301. Please use v3.0.14 / v3.1.1 / v4.0.0-rc.2 or above.

**Closed by kennytm** 2020-05-23 14:45 UTC
Labels: bug
